// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9LBjbXCz8HKOVPoWw1EE_PuoWi0oRC8',
    appId: '1:260813996329:web:88673cd0a799dac8787738',
    messagingSenderId: '260813996329',
    projectId: 'fir-series-6cc4b',
    authDomain: 'fir-series-6cc4b.firebaseapp.com',
    storageBucket: 'fir-series-6cc4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MfmhVK1_hSwz2Agyxoe9XvPmwmRC7Qo',
    appId: '1:260813996329:android:80b01e273866025d787738',
    messagingSenderId: '260813996329',
    projectId: 'fir-series-6cc4b',
    storageBucket: 'fir-series-6cc4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4K76fgaDIaR4huLzSi5QctfnkN6WWvsU',
    appId: '1:260813996329:ios:12453e0b5ed2c924787738',
    messagingSenderId: '260813996329',
    projectId: 'fir-series-6cc4b',
    storageBucket: 'fir-series-6cc4b.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4K76fgaDIaR4huLzSi5QctfnkN6WWvsU',
    appId: '1:260813996329:ios:5e4e443084c01af4787738',
    messagingSenderId: '260813996329',
    projectId: 'fir-series-6cc4b',
    storageBucket: 'fir-series-6cc4b.appspot.com',
    iosBundleId: 'com.example.firebaseSeries.RunnerTests',
  );
}
